g.images.input = Image("images/input.png");
g.images.input_left = Image("images/input-left.png");
g.images.input_right = Image("images/input-right.png");
g.images.progress = Image("images/progress.png");
g.images.progress_left = Image("images/progress-left.png");
g.images.progress_right = Image("images/progress-right.png");
g.images.bullet = Image("images/bullet.png");

g.input_border_radius = g.images.input_left.GetWidth();
g.input_width = 600 - g.input_border_radius * 2;
g.input_height = g.images.input_left.GetHeight();
g.input_padding = (g.input_height - g.images.progress_left.GetHeight()) / 2;

g.sprites.input = NULL;
g.sprites.input_left = NULL;
g.sprites.input_right = NULL;
g.sprites.progress = NULL;
g.sprites.progress_left = NULL;
g.sprites.progress_right = NULL;
g.sprites.bullets = NULL;
g.sprites.message = NULL;

g.time = NULL;
g.progress = NULL;
g.progress_bar = 0;
g.animations;
g.animations_at = 0;
g.root_mounted = 0;


// helper functions

fun init() {
   Window.SetBackgroundTopColor(0.118, 0.118, 0.18);         // https://catppuccin.com/palette - Mocha Base
   Window.SetBackgroundBottomColor(0.118, 0.118, 0.18);      // https://catppuccin.com/palette - Mocha Base

   screen_width = Window.GetWidth();
   screen_height = Window.GetHeight();
   input_image = g.images.input.Scale(g.input_width, g.input_height);

   g.sprites.input = Sprite(input_image);
   g.sprites.input_left = Sprite(g.images.input_left);
   g.sprites.input_right = Sprite(g.images.input_right);
   g.sprites.message = Sprite();

   position = centered(input_image);
   g.sprites.input.SetPosition(position.x, position.y);
   g.sprites.input_left.SetPosition(position.x - g.input_border_radius, position.y);
   g.sprites.input_right.SetPosition(position.x + g.input_width, position.y);
   g.sprites.message.SetPosition(10, 10);

   fade([g.sprites.input, g.sprites.input_left, g.sprites.input_right], 1000, 0, 1, ease_out_cubic);
}

fun centered(image, offset) {
   screen_width = Window.GetWidth();
   screen_height = Window.GetHeight();
   width = image.GetWidth();
   height = image.GetHeight();
   position.x = (screen_width - width) / 2 + (offset || 0);
   position.y = (screen_height - height) / 2 + (offset || 0);
   return position;
}

fun fade(elements, duration, opacity_start, opacity_end, easing) {
   if (!elements[0]) {
      elements[0] = elements;
   }
   animation.elements = elements;
   animation.start_time = g.time;
   animation.duration = duration / 1000;
   animation.opacity_start = opacity_start;
   animation.opacity_end = opacity_end;
   animation.easing = easing;
   g.animations[g.animations_at] = animation;
   g.animations_at++;

   for (i = 0; elements[i]; i++) {
      elements[i].SetOpacity(opacity_start);
   }
}

fun ease_out_cubic(t) {
   t = t - 1;
   return t * t * t + 1;
}

fun ease_in_cubic(t) {
   return t * t * t;
}


// plymouth callbacks

fun on_mode_normal() {
   // password -> normal means password is being validated
   if (g.sprites.bullets) {
      fade(g.sprites.bullets, 300, 1, 0.4, ease_out_cubic);
   }
}

fun on_mode_password(prompt, bullets) {
   // update password bullets, this can be improved by fading
   // the characters out, at least when the password is invalid
   // (bullets is 0 and previous screen was normal)
   if (bullets) {
      bullet_image = g.images.bullet;
      bullet_max_size = bullet_image.GetWidth();
      bullet_padding = 0.2;
      bullet_size = (g.input_width - g.input_padding * 2) / (bullets * (1 + bullet_padding) - bullet_padding);
      bullet_size = Math.Min(bullet_size, bullet_max_size);
      bullet_padding = bullet_size * bullet_padding;
      input_x = g.sprites.input.GetX() + g.input_padding;
      input_y = g.sprites.input.GetY();

      if (bullet_size < bullet_max_size) {
         bullet_image = bullet_image.Scale(bullet_size, bullet_size);
         for (i = 0; g.sprites.bullets[i]; i++) {
            g.sprites.bullets[i] = NULL;
         }
      }
   }

   for (i = 0; i < bullets; i++) {
      if (g.sprites.bullets[i]) {
         continue;
      }
      x = input_x + (bullet_size + bullet_padding) * i;
      y = input_y + (g.input_height - bullet_size) / 2;
      g.sprites.bullets[i] = Sprite(bullet_image);
      g.sprites.bullets[i].SetPosition(x, y);
   }
   for (i = bullets; g.sprites.bullets[i]; i++) {
      g.sprites.bullets[i] = NULL;
   }
}

fun on_root_mount() {
   // encryption was successful
   if (g.root_mounted) {
      return;
   }
   g.root_mounted = 1;
   g.progress_bar = 1;
   g.sprites.progress = Sprite(g.images.progress);
   g.sprites.progress_left = Sprite(g.images.progress_left);
   g.sprites.progress_right = Sprite(g.images.progress_right);

   fade(g.sprites.bullets, 200, 0.4, 0, ease_in_cubic);
}

fun on_progress(time, progress) {
   // track time for animations
   g.time = time;
   g.progress = progress;
}

fun on_update() {
   // fade animations
   if (g.time) {
      for (i = 0; i < g.animations_at; i++) {
         animation = g.animations[i];
         if (!animation) {
            continue;
         }
         if (!animation.start_time) {
            animation.start_time = g.time;
         }
         elapsed = g.time - animation.start_time;
         opacity = elapsed / animation.duration;
         opacity = animation.easing(opacity);
         opacity = Math.Min(1, opacity);
         opacity = animation.opacity_start + (animation.opacity_end - animation.opacity_start) * opacity;

         for (j = 0; animation.elements[j]; j++) {
            animation.elements[j].SetOpacity(opacity);
         }
         if (elapsed >= animation.duration) {
            g.animations[i] = NULL;
         }
      }
   }

   // progress bar
   if (g.progress && g.progress_bar) {
      width = (g.input_width - g.input_padding * 2) * g.progress;
      height = g.input_height - g.input_padding * 2;
      x = g.sprites.input.GetX() + g.input_padding;
      y = g.sprites.input.GetY() + g.input_padding;
      g.sprites.progress.SetImage(g.images.progress.Scale(width, height));
      g.sprites.progress.SetPosition(x, y);
      g.sprites.progress_left.SetPosition(x - g.input_border_radius, y);
      g.sprites.progress_right.SetPosition(x + width, y);
      g.progress_bar = g.progress < 1;
   }
}

fun on_message(text) {
   // show message, more than one should be visible at once,
   // and they should probably disappear
   image = Image.Text(text, 0.851, 0.851, 0.851, 1, "Sans 20");
   g.sprites.message.SetImage(image);
}

// TODO implement these?

fun on_status(status) {}

fun on_mode_question(prompt, input) {}

fun on_mode_prompt(prompt, input, is_secret) {}

fun on_quit() {}


Plymouth.SetRefreshRate(60);
Plymouth.SetDisplayNormalFunction(on_mode_normal);
Plymouth.SetDisplayPasswordFunction(on_mode_password);
Plymouth.SetRootMountedFunction(on_root_mount);
Plymouth.SetBootProgressFunction(on_progress);
Plymouth.SetRefreshFunction(on_update);
Plymouth.SetMessageFunction(on_message);
Plymouth.SetUpdateStatusFunction(on_status);
Plymouth.SetDisplayQuestionFunction(on_mode_question);
Plymouth.SetDisplayPromptFunction(on_mode_prompt);
Plymouth.SetQuitFunction(on_quit);


mode = Plymouth.GetMode();
if (mode != "boot") {
   image = Image.Text("goodbye", 0.851, 0.851, 0.851, 1, "Sans 20");
   position = centered(image);
   sprite = Sprite(image);
   sprite.SetPosition(position.x, position.y);
   fade(sprite, 3000, 0, 1, ease_out_cubic);
   return;
}

init();
