g.images.input = Image("images/input.png");
g.images.input_left = Image("images/input-left.png");
g.images.input_right = Image("images/input-right.png");
g.images.progress = Image("images/progress.png");
g.images.progress_left = Image("images/progress-left.png");
g.images.progress_right = Image("images/progress-right.png");
g.images.bullet = Image("images/bullet.png");

g.input_border_radius = NULL;
g.input_width = NULL;
g.input_height = NULL;
g.input_padding = NULL;
g.input_x = NULL;        // needed to position bullets while input is shaking
g.input_y = NULL;        // needed to position bullets while input is shaking

g.sprites.input = NULL;
g.sprites.input_left = NULL;
g.sprites.input_right = NULL;
g.sprites.progress = NULL;
g.sprites.progress_left = NULL;
g.sprites.progress_right = NULL;
g.sprites.bullets = NULL;
g.sprites.message = NULL;

g.mode = NULL;
g.time = NULL;
g.progress_bar = 0;
g.animations;
g.animations_at = 0;
g.root_mounted = 0;
g.layer1 = 1;
g.layer2 = 2;
g.layer3 = 3;


// helper functions

fun init() {
   Window.SetBackgroundTopColor(0.118, 0.118, 0.18);         // https://catppuccin.com/palette - Mocha Base
   Window.SetBackgroundBottomColor(0.118, 0.118, 0.18);      // https://catppuccin.com/palette - Mocha Base

   g.input_border_radius = g.images.input_left.GetWidth();
   g.input_width = 600 - g.input_border_radius * 2;
   g.input_height = g.images.input_left.GetHeight();
   g.input_padding = (g.input_height - g.images.progress_left.GetHeight()) / 2;

   input_image = g.images.input.Scale(g.input_width, g.input_height);
   position = centered(input_image);

   g.input_x = position.x;
   g.input_y = position.y;

   g.sprites.input = Sprite(input_image);
   g.sprites.input_left = Sprite(g.images.input_left);
   g.sprites.input_right = Sprite(g.images.input_right);
   g.sprites.input.SetPosition(g.input_x, g.input_y, g.layer1);
   g.sprites.input_left.SetPosition(g.input_x - g.input_border_radius, g.input_y, g.layer1);
   g.sprites.input_right.SetPosition(g.input_x + g.input_width, g.input_y, g.layer1);
   g.sprites.message = Sprite();
   g.sprites.message.SetPosition(10, 10, g.layer3);

   fade([g.sprites.input, g.sprites.input_left, g.sprites.input_right], 5000, 0, 0, 1, ease_out_cubic);
}

fun centered(image, offset) {
   screen_width = Window.GetWidth();
   screen_height = Window.GetHeight();
   width = image.GetWidth();
   height = image.GetHeight();
   position.x = (screen_width - width) / 2 + (offset || 0);
   position.y = (screen_height - height) / 2 + (offset || 0);
   return position;
}

fun new_animation(elements, duration, delay, callback) {
   if (!elements[0]) {
      elements[0] = elements;
   }
   animation.elements = elements;
   animation.duration = duration / 1000;
   animation.delay = delay / 1000;
   animation.callback = callback;
   if (animation.elements) {
      g.animations[g.animations_at] = animation;
      g.animations_at++;
   }
   return animation;
}

fun fade(element, duration, delay, opacity_start, opacity_end, easing) {
   animation = new_animation(element, duration, delay, fade_callback);
   animation.data.opacity_start = opacity_start;
   animation.data.opacity_end = opacity_end;
   animation.data.easing = easing;
   fade_callback(0, animation);
}

fun fade_callback(progress, animation) {
   opacity_start = animation.data.opacity_start;
   opacity_end = animation.data.opacity_end;
   opacity = animation.data.easing(progress);
   opacity = Math.Max(0, opacity);
   opacity = Math.Min(1, opacity);
   opacity = opacity_start + (opacity_end - opacity_start) * opacity;

   for (i = 0; animation.elements[i]; i++) {
      animation.elements[i].SetOpacity(opacity);
   }
}

fun shake(element, duration, delay) {
   // note that running shake on an already shaking (or otherwise moving)
   // element would break things badly
   animation = new_animation(element, duration, delay, shake_callback);
   for (i = 0; animation.elements[i]; i++) {
      animation.data.x_start[i] = animation.elements[i].GetX();
   }
}

fun shake_callback(progress, animation) {
   x_start = animation.data.x_start;
   x = ease_shake(progress) * 10;
   for (i = 0; animation.elements[i]; i++) {
      animation.elements[i].SetX(x_start[i] + x);
   }
}

fun ease_out_cubic(t) {
   t = t - 1;
   return t * t * t + 1;
}

fun ease_shake(t) {
   frequency = 6;
   decay = 3;
   return Math.Sin(t * frequency * 2 * Math.Pi) * exp(-decay * t);
}

fun exp(x) {
   sum = 1;
   term = 1;
   for (n = 1; n < 20; n++) {
      term *= x / n;
      sum += term;
   }
   return sum;
}

// plymouth callbacks

fun on_mode_normal() {
   // password is being validated
   if (g.mode == "password" && g.sprites.bullets) {
      fade(g.sprites.bullets, 250, 0, 1, 0.4, ease_out_cubic);
   }
   g.mode = "normal";
}

fun on_mode_password(prompt, bullets) {
   // invalid password
   if (g.mode == "normal" && g.sprites.bullets) {
      shake([g.sprites.input, g.sprites.input_left, g.sprites.input_right], 700, 0);
   }

   // update password bullets, this can be improved by fading
   // the characters out, at least when the password is invalid
   // (bullets is 0 and previous screen was normal)
   if (bullets) {
      bullet_image = g.images.bullet;
      bullet_max_size = bullet_image.GetWidth();
      bullet_padding = 0.2;
      bullet_size = (g.input_width - g.input_padding * 2) / (bullets * (1 + bullet_padding) - bullet_padding);
      bullet_size = Math.Min(bullet_size, bullet_max_size);
      bullet_padding = bullet_size * bullet_padding;

      if (bullet_size < bullet_max_size) {
         bullet_image = bullet_image.Scale(bullet_size, bullet_size);
         for (i = 0; g.sprites.bullets[i]; i++) {
            g.sprites.bullets[i] = NULL;
         }
      }
   }

   for (i = 0; i < bullets; i++) {
      if (g.sprites.bullets[i]) {
         continue;
      }
      x = g.input_x + g.input_padding + (bullet_size + bullet_padding) * i;
      y = g.input_y + (g.input_height - bullet_size) / 2;
      g.sprites.bullets[i] = Sprite(bullet_image);
      g.sprites.bullets[i].SetPosition(x, y, g.layer2);
   }
   for (i = bullets; g.sprites.bullets[i]; i++) {
      g.sprites.bullets[i] = NULL;
   }

   g.mode = "password";
}

fun on_root_mount() {
   // encryption was successful
   if (g.root_mounted) {
      return;
   }
   g.root_mounted = 1;
   g.progress_bar = 1;
   g.sprites.progress = Sprite(g.images.progress);
   g.sprites.progress_left = Sprite(g.images.progress_left);
   g.sprites.progress_right = Sprite(g.images.progress_right);

   fade(g.sprites.bullets, 250, 0, 0.4, 0, ease_out_cubic);
   fade([g.sprites.progress, g.sprites.progress_left, g.sprites.progress_right], 300, 0, 0, 1, ease_out_cubic);
}

fun on_progress(time, progress) {
   // animations
   g.time = time;
   for (i = 0; i < g.animations_at; i++) {
      animation = g.animations[i];
      if (!animation) {
         continue;
      }
      if (!animation.start_time) {
         animation.start_time = g.time;
      }
      elapsed = g.time - animation.start_time;
      if (elapsed < animation.delay) {
         continue;
      }
      elapsed -= animation.delay;
      animation_progress = elapsed / animation.duration;
      animation.callback(animation_progress, animation);
      if (animation_progress >= 1) {
         g.animations[i] = NULL;
      }
   }

   // progress bar
   if (g.progress_bar) {
      width = (g.input_width - g.input_padding * 2) * progress;
      height = g.input_height - g.input_padding * 2;
      x = g.input_x + g.input_padding;
      y = g.input_y + g.input_padding;
      g.sprites.progress.SetImage(g.images.progress.Scale(width, height));
      g.sprites.progress.SetPosition(x, y, g.layer3);
      g.sprites.progress_left.SetPosition(x - g.input_border_radius, y, g.layer3);
      g.sprites.progress_right.SetPosition(x + width, y, g.layer3);
      if (progress >= 1) {
         g.progress_bar = false;
         fade([g.sprites.progress, g.sprites.progress_left, g.sprites.progress_right], 300, 0, 1, 0, ease_out_cubic);
         fade([g.sprites.input, g.sprites.input_left, g.sprites.input_right], 300, 265, 1, 0, ease_out_cubic);
      }
   }
}

fun on_message(text) {
   // show message, more than one should be visible at once,
   // and they should probably disappear
   image = Image.Text(text, 0.851, 0.851, 0.851, 1, "Sans 20");
   g.sprites.message.SetImage(image);
}

// TODO implement these?

fun on_update() {}

fun on_status(status) {}

fun on_mode_question(prompt, input) {}

fun on_mode_prompt(prompt, input, is_secret) {}

fun on_quit() {}


Plymouth.SetRefreshRate(60);
Plymouth.SetDisplayNormalFunction(on_mode_normal);
Plymouth.SetDisplayPasswordFunction(on_mode_password);
Plymouth.SetRootMountedFunction(on_root_mount);
Plymouth.SetBootProgressFunction(on_progress);
Plymouth.SetMessageFunction(on_message);
Plymouth.SetRefreshFunction(on_update);
Plymouth.SetUpdateStatusFunction(on_status);
Plymouth.SetDisplayQuestionFunction(on_mode_question);
Plymouth.SetDisplayPromptFunction(on_mode_prompt);
Plymouth.SetQuitFunction(on_quit);


mode = Plymouth.GetMode();
if (mode != "boot") {
   image = Image.Text("goodbye", 0.851, 0.851, 0.851, 1, "Sans 20");
   position = centered(image);
   sprite = Sprite(image);
   sprite.SetPosition(position.x, position.y);
   fade(sprite, 3000, 0, 0, 1, ease_out_cubic);
   return;
}

init();
