#!/bin/dash

cd "$(dirname "$0")" || exit 1

input_height=100
progress_height=90
border_radius=12
bullet_font_size=120
bullet_font_family="Liberation-Sans"

input_color="#202020"
progress_color="#818181"
bullet_color="#787878"

rm *.png
magick -size 1x1 xc:"$input_color" -define png:compression-level=9 -define png:compression-strategy=0 -strip input.png
magick -size 1x1 xc:"$progress_color" -define png:compression-level=9 -define png:compression-strategy=0 -strip progress.png
magick \( -size "$((border_radius * 4))x$((input_height * 2))" xc:none -antialias -fill "$input_color" -draw "roundrectangle 0,0 $((border_radius * 4)),$((input_height * 2)) $((border_radius * 2)),$((border_radius * 2))" \) -crop $((border_radius * 2))x$((input_height * 2))+0+0 +repage -resize 50% -define png:compression-level=9 -define png:compression-strategy=0 -strip input-left.png
magick \( -size "$((border_radius * 4))x$((progress_height * 2))" xc:none -antialias -fill "$progress_color" -draw "roundrectangle 0,0 $((border_radius * 4)),$((progress_height * 2)) $((border_radius * 2)),$((border_radius * 2))" \) -crop $((border_radius * 2))x$((progress_height * 2))+0+0 +repage -resize 50% -define png:compression-level=9 -define png:compression-strategy=0 -strip progress-left.png
magick input-left.png -flop -define png:compression-level=9 -define png:compression-strategy=0 -strip input-right.png
magick progress-left.png -flop -define png:compression-level=9 -define png:compression-strategy=0 -strip progress-right.png
magick -background none -fill "$bullet_color" -font "$bullet_font_family" -pointsize "$bullet_font_size" -define text:antialias=true label:"*" -trim +repage -background none -extent "%[fx:max(w,h)]x%[fx:max(w,h)]" -gravity center -define png:compression-level=9 -define png:compression-strategy=0 -strip bullet.png
